# Generated by Django 3.1.6 on 2021-02-12 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textitem',
            name='time_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
