# Generated by Django 3.1.6 on 2021-02-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0002_textitem_time_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textitem',
            name='time_posted',
        ),
    ]
